Introduce an async version of GetAssetDataFromUrl
googleads/google-ads-dotnet pull request #307
Opened 2021-08-31 04:27 UTC by wub

Currently, the provided `MediaUtilities.GetAssetDataFromUrl` is synchronous, which isn't ideal for IO-bound scenarios. This pull request introduces an asynchronous version.

2021-09-08 19:10 UTC, AndrewMBurke requested changes
Thanks for the contribution! One suggestion to keep its behavior consistent with the existing method.

2021-09-09 00:42 UTC, wub commented on src/Util/MediaUtilities.cs
> +        public static async Task<byte[]> GetAssetDataFromUrlAsync(string assetUrl, GoogleAdsConfig config)
Hey @AndrewMBurke, this one returns a `Task<byte[]>` as it is an awaitable sister method to the one on Line 71. Generally, devs seeking out Async methods will know to `await` them.

IIRC, `.Result` can block threads and introduce deadlocks - happy to be corrected on this though!

2021-09-29 16:57 UTC, AnashOommen commented on src/Util/MediaUtilities.cs
> +        public static async Task<byte[]> GetAssetDataFromUrlAsync(string assetUrl, GoogleAdsConfig config)
I think the await call should chain here, so no need to call Result.

2021-09-29 16:57 UTC, AnashOommen approved these changes

2021-09-29 17:04 UTC, AndrewMBurke approved these changes

2021-10-05 18:52 UTC, merged