Update CHANGELOG.md for 16.2.0
googleads/google-ads-dotnet pull request #526
Opened 2023-07-06 15:34 UTC by Raibaz

2023-07-06 15:51 UTC, jradcliff approved these changes

2023-08-21 23:39 UTC, AnashOommen requested changes

2023-08-21 23:39 UTC, AnashOommen commented on CHANGELOG.md
> +16.2.0
We are at 17.0.0 now, so this should be 17.1.0, for instance.

2023-09-04 12:03 UTC, Raibaz commented
This is not needed anymore

2023-09-04 12:03 UTC, closed without merging