Add CustomAudience Resource Name helper
googleads/google-ads-dotnet pull request #528
Opened 2023-07-06 22:34 UTC by wub

Fixes #527

2023-07-07 09:33 UTC, Raibaz commented
Thanks for looking into this and putting together a PR!

2023-07-07 09:34 UTC, Raibaz approved these changes

2023-07-07 09:45 UTC, Raibaz requested changes
There's a typo in the return type of the `CustomAudience` function: it should be `string`, not `ctring` :)

2023-07-08 02:48 UTC, wub commented
Whoops, that's embarrassing... thanks @Raibaz!

2023-07-10 09:04 UTC, Raibaz approved these changes

2023-07-10 09:04 UTC, merged