Add GoogleAdsClient to DI container
googleads/google-ads-dotnet pull request #573
Opened 2024-09-03 14:44 UTC by Raibaz

This replicates #540 and rebases it on top of `main` to allow merging.

2024-09-03 17:46 UTC, sundquist requested changes

2024-09-04 10:00 UTC, Raibaz commented on Google.Ads.GoogleAds.Core/src/Lib/GoogleAdsClient.cs
> +    /// The Google Ads Client interface to allow for DI container configuration.
I think it's a fairly common acronym, but I don't see a reason not to spell it out entirely.

Changed it.

2024-09-04 10:00 UTC, Raibaz commented on Google.Ads.GoogleAds.Core/src/Lib/GoogleAdsClient.cs
> +        /// list of templates available for each supported version. E.g.</para>
Done.

2024-09-04 10:00 UTC, Raibaz commented on Google.Ads.GoogleAds.Extensions.DependencyInjection/src/GoogleAdsClientServiceCollectionExtensions.cs
> +            // add the setting to the DI container as options
Good point, made it consistent with the rest of the codebase with the capital letter and the period. Also spelt out dependency injection while I was there.

2024-09-04 13:45 UTC, Raibaz commented on Google.Ads.GoogleAds.Core/src/Lib/GoogleAdsClient.cs
> +        /// <para>E.g. <code>Services.V10</code> class contains predefined templates for v10 of
Done

2024-09-05 16:09 UTC, sundquist approved these changes
LGTM

2024-09-05 16:30 UTC, AnashOommen approved these changes

2024-09-05 18:50 UTC, merged

2024-11-13 09:06 UTC, sommmen commented
Hiya quick question - i must be blind or something, but i just updated the ads package and now i get the following error;

``` 
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Status(StatusCode="Internal", Detail="Error starting gRPC call. TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""", DebugException="Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:"""))
  Source=Google.Ads.Gax
  StackTrace:
   at Google.Ads.Gax.Interceptors.UnaryRpcInterceptor.<>c__DisplayClass1_0`2.<Intercept>b__0(Task`1 oldTask)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.<>c__DisplayClass4_0.<<CallAsync>g__WaitAndCallHandlers|0>d.MoveNext()
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
   at OPG.Jobs.Ads.GoogleAdsSyncJob.<OnRun>d__3.MoveNext() in C:\Repos\dotnet-api\OPG.Jobs\Ads\GoogleAdsSyncJob.cs:line 54

  This exception was originally thrown at this call stack:
    Google.Apis.Auth.OAuth2.Responses.TokenResponse.FromHttpResponseAsync(System.Net.Http.HttpResponseMessage, Google.Apis.Util.IClock, Google.Apis.Logging.ILogger)
    Google.Apis.Auth.OAuth2.Requests.RequestExtensions.PostFormAsync(object, System.Net.Http.HttpClient, string, System.Net.Http.Headers.AuthenticationHeaderValue, Google.Apis.Util.IClock, Google.Apis.Logging.ILogger, System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(string, Google.Apis.Auth.OAuth2.Requests.TokenRequest, System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.FetchTokenAsync(string, Google.Apis.Auth.OAuth2.Requests.TokenRequest, System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.RefreshTokenAsync(string, string, System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.UserCredential.RefreshTokenAsync(System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()
    Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(System.Threading.CancellationToken)
    Google.Apis.Auth.OAuth2.UserCredential.GetAccessTokenWithHeadersForRequestAsync(string, System.Threading.CancellationToken)
    Grpc.Auth.GoogleAuthInterceptors.FromCredential.AnonymousMethod__0(Grpc.Core.AuthInterceptorContext, Grpc.Core.Metadata)
    ...
    [Call Stack Truncated]

Inner Exception 1:
RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""", DebugException="Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""")

Inner Exception 2:
TokenResponseException: Error:"invalid_request", Description:"Missing required parameter: refresh_token", Uri:""

```

Startup.cs
`services.AddSingleton<GoogleAdsClient>();`

GoogleAdsSyncJob.cs
``` csharp
var customerService = _client.GetService(Services.V17.CustomerService);

var listAccessibleCustomersResponse = await customerService
    .ListAccessibleCustomersAsync(new ListAccessibleCustomersRequest(), CallSettings.FromCancellationToken(cancellationToken));
```

I then see in the release notes that auth can be added to DI now as mentioned in this PR.
So i try calling `AddGoogleAdsClient()` as mentioned in the tests and it failes to find the method.

The nuget browser also cannot see the extension;
![image](https://github.com/user-attachments/assets/6878557d-0213-431e-ba6c-d4c642051c45)

I also tried v18 instead of v17, same issue.

2024-11-13 14:06 UTC, Raibaz commented
Ah, you're right, the Google.Ads.GoogleAds.Extensions package wasn't updated in the last release of the client library.

We'll be publishing another release soon which will include these changes as well.

Sorry for the inconvenience.